### ISSUE TITLE
Restart the project?

### ISSUE THREAD

**Issue by Oymate** [sarim/Avrodroid#1]
Will this project be restarted as official app? If not maybe set as past project or something in readme :)

**Comment by sarim** [comment]
As the official (GBoard) input method provides a pretty good phonetic writing experience in android, this project isn't a priority.

**Comment by Oymate** [comment]
Do you have a Foss alternative, since it's a little hard to get gboard on *sanitized* phones

**Comment by Oymate** [comment]
Found one:https://gitlab.com/indicproject/indic-keyboard

Thanks again
